# Generated by cucumber-sinatra. (2014-10-06 12:08:52 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bkman.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = bookmarkmanager

class bookmarkmanagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  bookmarkmanagerWorld.new
end
